# Enter global values for your StaticAid site's JSON LD object here
# Any variable not marked as REQUIRED can be commented out if not applicable

# the function of your organization -- can currently be Library, Organization, or CollegeOrUniversity (case-sensitive) -- REQUIRED
instyType:

# a Wikidata, Freebase or other URI for your organization, if available
instyID:

# the commonly known name of your organization -- REQUIRED
instyName:

# your organization's URL -- REQUIRED
instyURL:

# is an image of your organization or its logo -- REQUIRED
instyImage:

# your org's Wikipedia URL, or a social media URL, if available
instySameAs:

# another name commonly used for your org, if available
instyAltName:

# your org's phpne number, eg xxx-xxx-xxxx -- REQUIRED
instyPhone:

# fields below collect your institution's address -- all are REQUIRED
instyStreetAddress:
instyCity:
instyState:
instyZipCode:

# is your org a branch of another entity, or do you have a parent organization? If yes, enter Yes below -- not, comment out the line below -- REQUIRED
parentOrg: Yes
# if Yes, fill out the below fields for your parent org, similar to the ones above

# parentType can currently be Organization, Corporation, or CollegeOrUniversity (case-sensitive) -- REQUIRED
parentType:

# parentID is a Wikidata, Freebase or other URI for your organization, if available
parentID:

# parentName is the commonly known name of your parent organization -- REQUIRED
parentName:

# parentURL is your parent organization's URL -- REQUIRED
parentURL:

# parentSameAs is your org's Wikipedia URL, or a social media URL, if available
parentSameAs:

# Other global variables for your StaticAid website:
# url:
# baseurl:
# email:
